package com.raithabharosahub.presentation.npk

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.raithabharosahub.data.local.dao.NpkDao
import com.raithabharosahub.data.local.entity.NpkEntity
import com.raithabharosahub.util.NpkRecommendationEngine
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.util.Date
import javax.inject.Inject

/**
 * ViewModel for NPK Input Centre.
 */
@HiltViewModel
class NpkViewModel @Inject constructor(
    private val npkDao: NpkDao,
    private val recommendationEngine: NpkRecommendationEngine
) : ViewModel() {

    private val _uiState = MutableStateFlow(NpkUiState())
    val uiState: StateFlow<NpkUiState> = _uiState.asStateFlow()

    init {
        loadHistory()
    }

    /**
     * Update a form field with validation.
     */
    fun updateField(field: NpkField, value: String) {
        _uiState.update { currentState ->
            val validationErrors = currentState.validationErrors.toMutableMap()
            
            when (field) {
                NpkField.NITROGEN, NpkField.PHOSPHORUS, NpkField.POTASSIUM -> {
                    // Validate numeric input (0-999)
                    val floatValue = value.toFloatOrNull()
                    if (floatValue == null || floatValue < 0f || floatValue > 999f) {
                        validationErrors[field.name] = "Must be between 0 and 999"
                    } else {
                        validationErrors.remove(field.name)
                    }
                }
                NpkField.LAB_NAME -> {
                    if (value.isBlank()) {
                        validationErrors[field.name] = "Lab name cannot be empty"
                    } else {
                        validationErrors.remove(field.name)
                    }
                }
                NpkField.TEST_DATE -> {
                    // Date validation handled by DatePicker
                    validationErrors.remove(field.name)
                }
            }

            currentState.copy(
                nitrogen = if (field == NpkField.NITROGEN) value else currentState.nitrogen,
                phosphorus = if (field == NpkField.PHOSPHORUS) value else currentState.phosphorus,
                potassium = if (field == NpkField.POTASSIUM) value else currentState.potassium,
                labName = if (field == NpkField.LAB_NAME) value else currentState.labName,
                testDate = if (field == NpkField.TEST_DATE) value.toLongOrNull() ?: currentState.testDate else currentState.testDate,
                validationErrors = validationErrors,
                isSaved = false
            )
        }
    }

    /**
     * Calculate recommendations based on current NPK values.
     */
    fun calculateRecommendations() {
        val state = _uiState.value
        
        val nitrogen = state.nitrogen.toFloatOrNull() ?: 0f
        val phosphorus = state.phosphorus.toFloatOrNull() ?: 0f
        val potassium = state.potassium.toFloatOrNull() ?: 0f
        
        // For now, use default crop "Paddy" - could be configurable later
        val crop = "Paddy"
        
        val recommendations = recommendationEngine.getRecommendations(
            nitrogen = nitrogen,
            phosphorus = phosphorus,
            potassium = potassium,
            crop = crop
        )
        
        _uiState.update { it.copy(recommendations = recommendations) }
    }

    /**
     * Save current entry to Room database.
     */
    fun saveEntry() {
        val state = _uiState.value
        
        val nitrogen = state.nitrogen.toFloatOrNull() ?: return
        val phosphorus = state.phosphorus.toFloatOrNull() ?: return
        val potassium = state.potassium.toFloatOrNull() ?: return
        
        if (state.labName.isBlank()) return
        
        viewModelScope.launch {
            val npkEntity = NpkEntity(
                id = 0, // Auto-generated by Room
                plotId = 1L, // Default plot ID - could be configurable later
                nitrogen = nitrogen,
                phosphorus = phosphorus,
                potassium = potassium,
                testDate = Date(state.testDate),
                labName = state.labName
            )
            
            npkDao.insert(npkEntity)
            
            // Clear form after save
            _uiState.update {
                it.copy(
                    nitrogen = "",
                    phosphorus = "",
                    potassium = "",
                    labName = "",
                    testDate = System.currentTimeMillis(),
                    recommendations = emptyList(),
                    isSaved = true
                )
            }
            
            // Reload history
            loadHistory()
        }
    }

    /**
     * Load NPK history from Room database.
     */
    private fun loadHistory() {
        viewModelScope.launch {
            npkDao.getByPlotId(1L).collect { history ->
                _uiState.update { it.copy(history = history) }
            }
        }
    }
}

/**
 * UI state for NPK Input Centre.
 */
data class NpkUiState(
    val nitrogen: String = "",
    val phosphorus: String = "",
    val potassium: String = "",
    val labName: String = "",
    val testDate: Long = System.currentTimeMillis(),
    val recommendations: List<NpkRecommendationEngine.NpkRecommendation> = emptyList(),
    val history: List<NpkEntity> = emptyList(),
    val isSaved: Boolean = false,
    val validationErrors: Map<String, String> = emptyMap()
)

/**
 * Form field identifiers.
 */
enum class NpkField {
    NITROGEN,
    PHOSPHORUS,
    POTASSIUM,
    LAB_NAME,
    TEST_DATE
}